import type { SectionSpec } from './builder';

/** Anglais général — Niveau A1 (débutant).
 *  2 sections · 9 unités · 30 leçons. */
export const GENERAL_A1: SectionSpec[] = [
  {
    id: 'gen-a1-s1',
    title: 'Premiers pas',
    units: [
      {
        id: 'gen-a1-u1',
        title: 'Salutations et présentations',
        subtitle: 'Dire bonjour, se présenter, être poli',
        icon: '👋',
        lessons: [
          {
            id: 'gen-a1-u1-l1',
            title: 'Dire bonjour',
            objective: 'Saluer quelqu’un et prendre congé selon le moment de la journée.',
            intro:
              "En anglais, la salutation dépend du moment de la journée. « Good morning » s'utilise jusqu'à midi, « Good afternoon » de midi à environ 18 h, et « Good evening » ensuite. « Hi » et « Hello » fonctionnent à toute heure.",
            note: {
              title: 'Formel ou informel ?',
              body: "« Hi » est amical, « Hello » est neutre, « Good morning » est plus formel. Au travail ou avec un inconnu, préférez « Hello » ou « Good morning ».",
              examples: [
                { en: 'Good morning, Mr. Clarke.', fr: 'Bonjour, M. Clarke.' },
                { en: 'Hi Sarah! How are you?', fr: 'Salut Sarah ! Comment vas-tu ?' },
              ],
            },
            vocab: [
              ['hello', 'bonjour', 'phrase', 'Hello, my name is Amina.', 'Bonjour, je m’appelle Amina.'],
              ['hi', 'salut', 'phrase'],
              ['good morning', 'bonjour (le matin)', 'phrase'],
              ['good afternoon', 'bonjour (l’après-midi)', 'phrase'],
              ['good evening', 'bonsoir', 'phrase'],
              ['goodbye', 'au revoir', 'phrase'],
              ['see you later', 'à plus tard', 'phrase'],
              ['good night', 'bonne nuit', 'phrase'],
              ['welcome', 'bienvenue', 'phrase'],
            ],
            sentences: [
              ['Hello, how are you?', 'Bonjour, comment allez-vous ?'],
              ['I am fine, thank you.', 'Je vais bien, merci.'],
              ['Good morning, everyone.', 'Bonjour à tous.'],
              ['See you tomorrow.', 'À demain.'],
            ],
            grammar: [
              {
                topicId: 'verb-be-present',
                title: 'Le verbe « to be » au présent',
                rule: "Avec « I », le verbe « be » devient « am » ; avec « you / we / they », « are » ; avec « he / she / it », « is ». On ne dit jamais « I is ».",
                en: 'I am fine.',
                fr: 'Je vais bien.',
                wrong: ['I is fine.', 'I are fine.', 'I be fine.'],
                blank: 'am',
              },
            ],
            estimatedMinutes: 5,
          },
          {
            id: 'gen-a1-u1-l2',
            title: 'Se présenter',
            objective: 'Donner son nom, sa nationalité et son métier.',
            intro:
              "Pour se présenter, l'anglais utilise très souvent le verbe « to be » : « I am… ». La forme contractée « I'm » est la plus courante à l'oral.",
            note: {
              title: 'Les contractions',
              body: "I am → I'm · you are → you're · he is → he's. Les contractions sont normales à l'oral et dans un e-mail courant ; on les évite dans un texte très formel.",
            },
            vocab: [
              ['name', 'nom / prénom', 'n', 'My name is Yusuf.', 'Je m’appelle Yusuf.'],
              ['nice to meet you', 'enchanté(e)', 'phrase'],
              ['country', 'pays', 'n'],
              ['job', 'métier', 'n'],
              ['teacher', 'enseignant(e)', 'n'],
              ['engineer', 'ingénieur(e)', 'n'],
              ['student', 'étudiant(e)', 'n'],
              ['nurse', 'infirmier(ère)', 'n'],
              ['driver', 'chauffeur', 'n'],
            ],
            sentences: [
              ['My name is Sofia.', 'Je m’appelle Sofia.'],
              ['I am from Nigeria.', 'Je viens du Nigeria.'],
              ['I am an engineer.', 'Je suis ingénieur.'],
              ['Nice to meet you.', 'Enchanté(e).'],
            ],
            grammar: [
              {
                topicId: 'articles-a-an',
                title: '« a » ou « an » ?',
                rule: "On utilise « an » devant un son de voyelle (an engineer, an apple) et « a » devant un son de consonne (a teacher, a job).",
                en: 'She is an engineer.',
                fr: 'Elle est ingénieure.',
                wrong: ['She is a engineer.', 'She is engineer.', 'She is the engineer a.'],
                blank: 'an',
              },
              {
                topicId: 'verb-be-present',
                title: 'Métiers avec « to be »',
                rule: "En anglais, un métier est précédé d'un article : « I am a nurse », jamais « I am nurse ».",
                en: 'I am a nurse.',
                fr: 'Je suis infirmière.',
                wrong: ['I am nurse.', 'I nurse am.', 'I am the nurse a.'],
                blank: 'a',
              },
            ],
          },
          {
            id: 'gen-a1-u1-l3',
            title: 'Les nombres de 0 à 100',
            objective: 'Compter, donner son âge et un numéro de téléphone.',
            intro:
              "Les nombres de 13 à 19 se terminent en « -teen » ; les dizaines en « -ty ». L'accent tonique change : thirTEEN (13) contre THIRty (30).",
            vocab: [
              ['one', 'un'],
              ['five', 'cinq'],
              ['ten', 'dix'],
              ['thirteen', 'treize'],
              ['thirty', 'trente'],
              ['fifteen', 'quinze'],
              ['fifty', 'cinquante'],
              ['twenty-one', 'vingt et un'],
              ['a hundred', 'cent'],
              ['number', 'numéro / nombre', 'n'],
            ],
            sentences: [
              ['I am twenty-eight years old.', 'J’ai vingt-huit ans.'],
              ['My phone number is zero five one.', 'Mon numéro de téléphone est zéro cinq un.'],
              ['There are thirty students.', 'Il y a trente étudiants.'],
            ],
            grammar: [
              {
                topicId: 'age-with-be',
                title: 'L’âge se dit avec « to be »',
                rule: "L'anglais dit « I am 28 (years old) », littéralement « je suis 28 ». On n'utilise jamais « have » pour l'âge.",
                en: 'She is twelve years old.',
                fr: 'Elle a douze ans.',
                wrong: ['She has twelve years old.', 'She has twelve years.', 'She is twelve years.'],
                blank: 'is',
              },
            ],
          },
          {
            id: 'gen-a1-u1-l4',
            title: 'Politesse et demandes simples',
            objective: 'Remercier, s’excuser et demander poliment.',
            intro:
              "Trois formules ouvrent presque toutes les portes : « please » (s'il vous plaît), « thank you » (merci) et « excuse me » (excusez-moi, pour aborder quelqu'un). « Sorry » sert plutôt à s'excuser après coup.",
            vocab: [
              ['please', 's’il vous plaît', 'phrase'],
              ['thank you', 'merci', 'phrase'],
              ['you’re welcome', 'de rien', 'phrase'],
              ['excuse me', 'excusez-moi', 'phrase'],
              ['sorry', 'désolé(e)', 'adj'],
              ['can you help me?', 'pouvez-vous m’aider ?', 'phrase'],
              ['of course', 'bien sûr', 'phrase'],
              ['no problem', 'pas de problème', 'phrase'],
            ],
            sentences: [
              ['Excuse me, can you help me?', 'Excusez-moi, pouvez-vous m’aider ?'],
              ['Thank you very much.', 'Merci beaucoup.'],
              ['Could you repeat, please?', 'Pourriez-vous répéter, s’il vous plaît ?'],
            ],
            grammar: [
              {
                topicId: 'modal-can-request',
                title: '« Can » pour demander',
                rule: "Après « can », le verbe reste à l'infinitif sans « to » : « Can you help me? » et non « Can you to help me? ».",
                en: 'Can you help me, please?',
                fr: 'Pouvez-vous m’aider, s’il vous plaît ?',
                wrong: ['Can you to help me, please?', 'Can you helping me, please?', 'You can help me?'],
                blank: 'help',
              },
            ],
            dialogue: {
              context: 'Dans la rue, Amina aborde un passant.',
              lines: [
                { speaker: 'Amina', en: 'Excuse me, can you help me?', fr: 'Excusez-moi, pouvez-vous m’aider ?' },
                { speaker: 'Passer-by', en: 'Of course. What do you need?', fr: 'Bien sûr. De quoi avez-vous besoin ?' },
                { speaker: 'Amina', en: 'Where is the train station?', fr: 'Où se trouve la gare ?' },
                { speaker: 'Passer-by', en: 'It is behind the bank. Two minutes from here.', fr: 'Elle est derrière la banque. À deux minutes d’ici.' },
                { speaker: 'Amina', en: 'Thank you very much!', fr: 'Merci beaucoup !' },
              ],
              statements: [
                { en: 'Amina is looking for the train station.', isTrue: true, explanation: 'Elle demande « Where is the train station? ».' },
                { en: 'The station is in front of the bank.', isTrue: false, explanation: 'Le passant dit « behind the bank » — derrière la banque.' },
              ],
            },
          },
        ],
      },
      {
        id: 'gen-a1-u2',
        title: 'La famille et les gens',
        subtitle: 'Parler de ses proches et décrire quelqu’un',
        icon: '👨‍👩‍👧',
        lessons: [
          {
            id: 'gen-a1-u2-l1',
            title: 'La famille proche',
            objective: 'Nommer les membres de sa famille.',
            intro:
              "Le vocabulaire familial anglais distingue peu le côté paternel du côté maternel : « uncle » et « aunt » servent des deux côtés. « Parents » désigne le père et la mère, pas la famille élargie — attention au faux ami.",
            vocab: [
              ['mother', 'mère', 'n'],
              ['father', 'père', 'n'],
              ['parents', 'les parents (père et mère)', 'n'],
              ['brother', 'frère', 'n'],
              ['sister', 'sœur', 'n'],
              ['son', 'fils', 'n'],
              ['daughter', 'fille (de quelqu’un)', 'n'],
              ['wife', 'épouse', 'n'],
              ['husband', 'mari', 'n'],
              ['child / children', 'enfant / enfants', 'n'],
            ],
            sentences: [
              ['I have two sisters and one brother.', 'J’ai deux sœurs et un frère.'],
              ['My father is a driver.', 'Mon père est chauffeur.'],
              ['She has three children.', 'Elle a trois enfants.'],
            ],
            grammar: [
              {
                topicId: 'have-has',
                title: '« have » ou « has » ?',
                rule: "« He », « she » et « it » prennent « has » ; toutes les autres personnes prennent « have ».",
                en: 'She has three children.',
                fr: 'Elle a trois enfants.',
                wrong: ['She have three children.', 'She haves three children.', 'She is have three children.'],
                blank: 'has',
              },
            ],
          },
          {
            id: 'gen-a1-u2-l2',
            title: 'Décrire une personne',
            objective: 'Décrire l’apparence et le caractère.',
            intro:
              "En anglais, l'adjectif se place avant le nom et ne s'accorde jamais : « a tall woman », « two tall women ».",
            note: {
              title: 'Ordre des mots',
              body: "Adjectif + nom, toujours dans cet ordre : « a young engineer ». On ne dit pas « an engineer young ».",
            },
            vocab: [
              ['tall', 'grand(e)', 'adj'],
              ['short', 'petit(e) / court(e)', 'adj'],
              ['young', 'jeune', 'adj'],
              ['old', 'âgé(e) / vieux', 'adj'],
              ['kind', 'gentil(le)', 'adj'],
              ['funny', 'drôle', 'adj'],
              ['serious', 'sérieux(se)', 'adj'],
              ['hair', 'cheveux', 'n'],
              ['eyes', 'yeux', 'n'],
            ],
            sentences: [
              ['My sister is tall and funny.', 'Ma sœur est grande et drôle.'],
              ['He has short hair.', 'Il a les cheveux courts.'],
              ['She is a very kind person.', 'C’est une personne très gentille.'],
            ],
            grammar: [
              {
                topicId: 'adjective-order',
                title: 'L’adjectif ne s’accorde pas',
                rule: "L'adjectif anglais est invariable : « tall » ne devient jamais « talls ».",
                en: 'They are tall students.',
                fr: 'Ce sont des étudiants grands.',
                wrong: ['They are talls students.', 'They are students tall.', 'They are tall student.'],
                blank: 'tall',
              },
            ],
          },
          {
            id: 'gen-a1-u2-l3',
            title: 'À qui est-ce ? Les possessifs',
            objective: 'Utiliser my, your, his, her et le génitif ’s.',
            intro:
              "Le possessif anglais s'accorde avec le POSSESSEUR, pas avec l'objet : « his sister » (la sœur d'un homme), « her sister » (la sœur d'une femme).",
            note: {
              title: 'Le génitif ’s',
              body: "Pour dire « la voiture de Paul », l'anglais met le possesseur d'abord : « Paul's car ». Avec un pluriel en -s, on ajoute seulement l'apostrophe : « my parents' house ».",
            },
            vocab: [
              ['my', 'mon / ma / mes'],
              ['your', 'ton / votre'],
              ['his', 'son (à lui)'],
              ['her', 'son (à elle)'],
              ['our', 'notre / nos'],
              ['their', 'leur / leurs'],
              ['friend', 'ami(e)', 'n'],
              ['neighbour', 'voisin(e)', 'n'],
            ],
            sentences: [
              ['This is my friend Karim.', 'Voici mon ami Karim.'],
              ['Her brother lives in London.', 'Son frère (à elle) habite à Londres.'],
              ['That is Sarah’s car.', 'C’est la voiture de Sarah.'],
            ],
            grammar: [
              {
                topicId: 'possessives',
                title: 'Possessif : on suit le possesseur',
                rule: "« her » quand le possesseur est une femme, « his » quand c'est un homme — quel que soit l'objet possédé.",
                en: 'Sarah is with her brother.',
                fr: 'Sarah est avec son frère.',
                wrong: ['Sarah is with his brother.', 'Sarah is with her’s brother.', 'Sarah is with she brother.'],
                blank: 'her',
              },
            ],
          },
        ],
      },
      {
        id: 'gen-a1-u3',
        title: 'La maison',
        subtitle: 'Décrire son logement et ce qu’il contient',
        icon: '🏠',
        lessons: [
          {
            id: 'gen-a1-u3-l1',
            title: 'Les pièces de la maison',
            objective: 'Nommer les pièces et dire où l’on est.',
            intro:
              "Attention à deux faux amis : « a room » est une pièce (pas seulement une chambre), et « a library » est une bibliothèque publique — la librairie se dit « a bookshop ».",
            vocab: [
              ['house', 'maison', 'n'],
              ['flat / apartment', 'appartement', 'n'],
              ['room', 'pièce', 'n'],
              ['kitchen', 'cuisine', 'n'],
              ['bedroom', 'chambre', 'n'],
              ['bathroom', 'salle de bain', 'n'],
              ['living room', 'salon', 'n'],
              ['garden', 'jardin', 'n'],
              ['door', 'porte', 'n'],
              ['window', 'fenêtre', 'n'],
            ],
            sentences: [
              ['My flat has two bedrooms.', 'Mon appartement a deux chambres.'],
              ['She is in the kitchen.', 'Elle est dans la cuisine.'],
              ['The living room is very bright.', 'Le salon est très lumineux.'],
            ],
            grammar: [
              {
                topicId: 'prepositions-place',
                title: 'in, on, at',
                rule: "« in » pour un espace fermé (in the kitchen), « on » pour une surface (on the table), « at » pour un point ou une adresse (at home, at work).",
                en: 'The keys are on the table.',
                fr: 'Les clés sont sur la table.',
                wrong: ['The keys are in the table.', 'The keys are at the table.', 'The keys are on table.'],
                blank: 'on',
              },
            ],
          },
          {
            id: 'gen-a1-u3-l2',
            title: 'Meubles et objets du quotidien',
            objective: 'Décrire ce qu’il y a dans une pièce.',
            intro:
              "« There is » annonce un élément au singulier, « there are » un pluriel. C'est la structure de base pour décrire un lieu.",
            note: {
              title: 'There is / There are',
              body: "There is a table. (singulier) · There are two chairs. (pluriel) · Forme négative : There isn't a lift. / There aren't any chairs.",
              examples: [
                { en: 'There is a sofa in the living room.', fr: 'Il y a un canapé dans le salon.' },
                { en: 'There are three windows.', fr: 'Il y a trois fenêtres.' },
              ],
            },
            vocab: [
              ['table', 'table', 'n'],
              ['chair', 'chaise', 'n'],
              ['bed', 'lit', 'n'],
              ['sofa', 'canapé', 'n'],
              ['fridge', 'réfrigérateur', 'n'],
              ['cupboard', 'placard', 'n'],
              ['lamp', 'lampe', 'n'],
              ['mirror', 'miroir', 'n'],
              ['carpet', 'tapis', 'n'],
            ],
            sentences: [
              ['There is a lamp next to the bed.', 'Il y a une lampe à côté du lit.'],
              ['There are four chairs in the kitchen.', 'Il y a quatre chaises dans la cuisine.'],
              ['There isn’t a mirror in the bathroom.', 'Il n’y a pas de miroir dans la salle de bain.'],
            ],
            grammar: [
              {
                topicId: 'there-is-are',
                title: 'There is / There are',
                rule: "« There is » + nom singulier, « There are » + nom pluriel. L'accord se fait avec ce qui suit, pas avec « there ».",
                en: 'There are two chairs in the room.',
                fr: 'Il y a deux chaises dans la pièce.',
                wrong: ['There is two chairs in the room.', 'It has two chairs in the room.', 'There have two chairs in the room.'],
                blank: 'are',
              },
            ],
          },
          {
            id: 'gen-a1-u3-l3',
            title: 'Où est-ce ? Les prépositions de lieu',
            objective: 'Situer un objet précisément.',
            intro:
              "Ces petites prépositions changent tout le sens d'une phrase. Elles s'apprennent par l'image plutôt que par la traduction.",
            vocab: [
              ['in', 'dans', 'prep'],
              ['on', 'sur', 'prep'],
              ['under', 'sous', 'prep'],
              ['next to', 'à côté de', 'prep'],
              ['behind', 'derrière', 'prep'],
              ['in front of', 'devant', 'prep'],
              ['between', 'entre', 'prep'],
              ['near', 'près de', 'prep'],
            ],
            sentences: [
              ['The cat is under the table.', 'Le chat est sous la table.'],
              ['The bank is between the school and the hotel.', 'La banque est entre l’école et l’hôtel.'],
              ['My car is in front of the house.', 'Ma voiture est devant la maison.'],
            ],
            grammar: [
              {
                topicId: 'prepositions-place',
                title: '« in front of » ≠ « in front »',
                rule: "« in front of » exige toujours « of » devant le nom : « in front of the house ».",
                en: 'The taxi is in front of the hotel.',
                fr: 'Le taxi est devant l’hôtel.',
                wrong: ['The taxi is in front the hotel.', 'The taxi is front of the hotel.', 'The taxi is on front of the hotel.'],
                blank: 'in front of',
              },
            ],
          },
        ],
      },
      {
        id: 'gen-a1-u4',
        title: 'La nourriture',
        subtitle: 'Manger, commander, faire ses courses',
        icon: '🍽️',
        lessons: [
          {
            id: 'gen-a1-u4-l1',
            title: 'Aliments et boissons',
            objective: 'Nommer les aliments courants et dire ce que l’on aime.',
            intro:
              "Après « like », « love » ou « hate », le nom au pluriel sans article exprime le goût général : « I like apples » = j'aime les pommes en général.",
            vocab: [
              ['bread', 'pain', 'n'],
              ['rice', 'riz', 'n'],
              ['meat', 'viande', 'n'],
              ['fish', 'poisson', 'n'],
              ['vegetables', 'légumes', 'n'],
              ['fruit', 'fruit(s)', 'n'],
              ['water', 'eau', 'n'],
              ['milk', 'lait', 'n'],
              ['tea', 'thé', 'n'],
              ['coffee', 'café', 'n'],
            ],
            sentences: [
              ['I like rice and fish.', 'J’aime le riz et le poisson.'],
              ['She doesn’t drink coffee.', 'Elle ne boit pas de café.'],
              ['We eat vegetables every day.', 'Nous mangeons des légumes tous les jours.'],
            ],
            grammar: [
              {
                topicId: 'present-simple-negative',
                title: 'La négation au présent simple',
                rule: "« don't » pour I / you / we / they, « doesn't » pour he / she / it. Après « doesn't », le verbe perd son -s : « She doesn't drink ».",
                en: 'She doesn’t drink coffee.',
                fr: 'Elle ne boit pas de café.',
                wrong: ['She doesn’t drinks coffee.', 'She don’t drink coffee.', 'She not drink coffee.'],
                blank: 'doesn’t',
              },
            ],
          },
          {
            id: 'gen-a1-u4-l2',
            title: 'Au restaurant',
            objective: 'Commander un repas et demander l’addition.',
            intro:
              "Au restaurant, « I would like… » (souvent contracté en « I'd like… ») est bien plus poli que « I want… ».",
            vocab: [
              ['menu', 'menu / carte', 'n'],
              ['waiter', 'serveur', 'n'],
              ['order', 'commander', 'v'],
              ['bill / check', 'addition', 'n'],
              ['starter', 'entrée', 'n'],
              ['main course', 'plat principal', 'n'],
              ['dessert', 'dessert', 'n'],
              ['table for two', 'table pour deux', 'phrase'],
            ],
            sentences: [
              ['I’d like the fish, please.', 'Je voudrais le poisson, s’il vous plaît.'],
              ['Could we have the bill, please?', 'Pourrions-nous avoir l’addition, s’il vous plaît ?'],
              ['A table for two, please.', 'Une table pour deux, s’il vous plaît.'],
            ],
            grammar: [
              {
                topicId: 'would-like',
                title: '« I would like » — la commande polie',
                rule: "« I'd like » est suivi d'un nom ou d'un verbe à l'infinitif avec « to » : « I'd like a coffee » / « I'd like to order ».",
                en: 'I would like to order, please.',
                fr: 'Je voudrais commander, s’il vous plaît.',
                wrong: ['I would like order, please.', 'I would like ordering, please.', 'I will like to order, please.'],
                blank: 'to order',
              },
            ],
            dialogue: {
              context: 'Au restaurant, un serveur prend la commande.',
              lines: [
                { speaker: 'Waiter', en: 'Good evening. Are you ready to order?', fr: 'Bonsoir. Êtes-vous prêts à commander ?' },
                { speaker: 'Customer', en: 'Yes. I’d like the chicken, please.', fr: 'Oui. Je voudrais le poulet, s’il vous plaît.' },
                { speaker: 'Waiter', en: 'And to drink?', fr: 'Et comme boisson ?' },
                { speaker: 'Customer', en: 'Just water, thank you.', fr: 'Juste de l’eau, merci.' },
              ],
              statements: [
                { en: 'The customer orders fish.', isTrue: false, explanation: 'Le client commande « the chicken » — du poulet.' },
                { en: 'The customer wants water.', isTrue: true, explanation: 'Il répond « Just water, thank you ».' },
              ],
            },
          },
          {
            id: 'gen-a1-u4-l3',
            title: 'Combien ? Dénombrables et indénombrables',
            objective: 'Utiliser some, any, much et many correctement.',
            intro:
              "L'anglais sépare ce qui se compte (two apples) de ce qui ne se compte pas (water, rice, money). Cette distinction commande le choix de « many » ou « much ».",
            note: {
              title: 'some / any / much / many',
              body: "« some » dans les phrases affirmatives, « any » dans les négatives et les questions. « many » + dénombrable pluriel, « much » + indénombrable.",
              examples: [
                { en: 'There is some milk in the fridge.', fr: 'Il y a du lait dans le frigo.' },
                { en: 'How many apples do you want?', fr: 'Combien de pommes veux-tu ?' },
              ],
            },
            vocab: [
              ['some', 'du / de la / des'],
              ['any', 'de (négation/question)'],
              ['many', 'beaucoup de (dénombrable)'],
              ['much', 'beaucoup de (indénombrable)'],
              ['a bottle of', 'une bouteille de', 'phrase'],
              ['a glass of', 'un verre de', 'phrase'],
              ['a piece of', 'un morceau de', 'phrase'],
            ],
            sentences: [
              ['There isn’t any bread.', 'Il n’y a pas de pain.'],
              ['How many eggs do we need?', 'Combien d’œufs nous faut-il ?'],
              ['I don’t drink much tea.', 'Je ne bois pas beaucoup de thé.'],
            ],
            grammar: [
              {
                topicId: 'countable-uncountable',
                title: 'many ou much ?',
                rule: "« many » se met devant un nom qui se compte (eggs, chairs) ; « much » devant un nom qui ne se compte pas (water, money, time).",
                en: 'How many eggs do you need?',
                fr: 'Combien d’œufs vous faut-il ?',
                wrong: ['How much eggs do you need?', 'How many egg do you need?', 'How many eggs you need?'],
                blank: 'many',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'gen-a1-s2',
    title: 'La vie de tous les jours',
    units: [
      {
        id: 'gen-a1-u5',
        title: 'Le temps et la routine',
        subtitle: 'L’heure, les jours, les habitudes',
        icon: '⏰',
        lessons: [
          {
            id: 'gen-a1-u5-l1',
            title: 'L’heure et les jours',
            objective: 'Dire l’heure et parler des jours de la semaine.',
            intro:
              "Pour l'heure, l'anglais utilise « at » : at seven o'clock. Pour les jours, « on » : on Monday. Pour les mois et les années, « in » : in June, in 2026.",
            vocab: [
              ['Monday', 'lundi', 'n'],
              ['Tuesday', 'mardi', 'n'],
              ['Wednesday', 'mercredi', 'n'],
              ['Saturday', 'samedi', 'n'],
              ['Sunday', 'dimanche', 'n'],
              ['today', 'aujourd’hui', 'adv'],
              ['tomorrow', 'demain', 'adv'],
              ['week', 'semaine', 'n'],
              ['o’clock', 'heure pile', 'phrase'],
              ['half past', 'et demie', 'phrase'],
            ],
            sentences: [
              ['It is half past seven.', 'Il est sept heures et demie.'],
              ['I work on Saturday.', 'Je travaille le samedi.'],
              ['The meeting is at nine o’clock.', 'La réunion est à neuf heures.'],
            ],
            grammar: [
              {
                topicId: 'prepositions-time',
                title: 'at / on / in pour le temps',
                rule: "« at » + heure · « on » + jour ou date · « in » + mois, saison, année.",
                en: 'The class starts at eight o’clock.',
                fr: 'Le cours commence à huit heures.',
                wrong: ['The class starts in eight o’clock.', 'The class starts on eight o’clock.', 'The class starts to eight o’clock.'],
                blank: 'at',
              },
            ],
          },
          {
            id: 'gen-a1-u5-l2',
            title: 'Ma journée type',
            objective: 'Décrire ses habitudes au présent simple.',
            intro:
              "Le présent simple sert à décrire ce qui est habituel ou vrai en général. C'est le temps de la routine.",
            note: {
              title: 'Le -s de la troisième personne',
              body: "Avec he / she / it, on ajoute -s au verbe : « She works ». Les verbes en -o, -ch, -sh, -ss prennent -es : « He goes », « She watches ».",
              examples: [
                { en: 'She works in London.', fr: 'Elle travaille à Londres.' },
                { en: 'He goes to work by bus.', fr: 'Il va au travail en bus.' },
              ],
            },
            vocab: [
              ['wake up', 'se réveiller', 'v'],
              ['get up', 'se lever', 'v'],
              ['have breakfast', 'prendre le petit-déjeuner', 'phrase'],
              ['go to work', 'aller au travail', 'phrase'],
              ['start', 'commencer', 'v'],
              ['finish', 'terminer', 'v'],
              ['come home', 'rentrer à la maison', 'phrase'],
              ['go to bed', 'aller se coucher', 'phrase'],
              ['always', 'toujours', 'adv'],
              ['never', 'jamais', 'adv'],
            ],
            sentences: [
              ['I wake up at six every day.', 'Je me réveille à six heures tous les jours.'],
              ['She works in London.', 'Elle travaille à Londres.'],
              ['He never goes to bed late.', 'Il ne se couche jamais tard.'],
            ],
            grammar: [
              {
                topicId: 'present-simple',
                title: 'Present simple — le -s de la 3ᵉ personne',
                rule: "Avec « she », le verbe au présent simple prend « -s » : « She works ». Sans « -s », la phrase est fausse.",
                en: 'She works in London.',
                fr: 'Elle travaille à Londres.',
                wrong: ['She work in London.', 'She working in London.', 'She is work in London.'],
                blank: 'works',
              },
              {
                topicId: 'adverbs-frequency',
                title: 'Place des adverbes de fréquence',
                rule: "« always », « never », « often » se placent avant le verbe principal mais après « to be » : « He never eats… » / « He is never late ».",
                en: 'He never goes to bed late.',
                fr: 'Il ne se couche jamais tard.',
                wrong: ['He goes never to bed late.', 'Never he goes to bed late.', 'He never go to bed late.'],
                blank: 'never',
              },
            ],
            reading: {
              title: 'A day with Nadia',
              text: "Nadia is a nurse in Manchester. She wakes up at half past five and has breakfast with her husband. She takes the bus at seven and starts work at eight. The hospital is busy, so she rarely has lunch before two o'clock. She finishes at six and comes home at seven. In the evening she reads or watches a film. She never goes to bed after eleven, because she gets up early.",
              questions: [
                {
                  prompt: 'What time does Nadia start work?',
                  options: ['At seven', 'At eight', 'At half past five', 'At two'],
                  answer: 1,
                  explanation: 'Le texte dit « starts work at eight ». « Takes the bus at seven » est le trajet, pas le début du travail.',
                },
                {
                  prompt: 'Why does she rarely have lunch before two?',
                  options: ['She is not hungry', 'The hospital is busy', 'She works at home', 'She gets up late'],
                  answer: 1,
                  explanation: '« The hospital is busy, so she rarely has lunch before two o’clock. »',
                },
                {
                  prompt: 'What does Nadia do in the evening?',
                  options: ['She works', 'She goes to the hospital', 'She reads or watches a film', 'She takes the bus'],
                  answer: 2,
                  explanation: '« In the evening she reads or watches a film. »',
                },
              ],
            },
          },
          {
            id: 'gen-a1-u5-l3',
            title: 'Poser des questions au présent',
            objective: 'Construire des questions avec do / does et les mots interrogatifs.',
            intro:
              "L'anglais ne fait pas l'inversion comme le français : il ajoute un auxiliaire. « Do you work? » et non « Work you? ».",
            vocab: [
              ['what', 'quoi / que'],
              ['where', 'où'],
              ['when', 'quand'],
              ['who', 'qui'],
              ['why', 'pourquoi'],
              ['how', 'comment'],
              ['how often', 'à quelle fréquence', 'phrase'],
            ],
            sentences: [
              ['Where do you work?', 'Où travaillez-vous ?'],
              ['What time does the shop open?', 'À quelle heure le magasin ouvre-t-il ?'],
              ['Why does he take the bus?', 'Pourquoi prend-il le bus ?'],
            ],
            grammar: [
              {
                topicId: 'questions-do-does',
                title: 'Questions avec do / does',
                rule: "Après « does », le verbe revient à sa forme de base, sans -s : « Does she work? » et non « Does she works? ».",
                en: 'Does she work here?',
                fr: 'Est-ce qu’elle travaille ici ?',
                wrong: ['Does she works here?', 'Do she work here?', 'She does work here?'],
                blank: 'work',
              },
            ],
          },
        ],
      },
      {
        id: 'gen-a1-u6',
        title: 'Vêtements et achats',
        subtitle: 'Acheter, essayer, payer',
        icon: '🛍️',
        lessons: [
          {
            id: 'gen-a1-u6-l1',
            title: 'Les vêtements',
            objective: 'Nommer les vêtements et décrire une tenue.',
            intro:
              "Certains vêtements sont toujours pluriels en anglais : trousers, jeans, shorts, glasses. On dit « my trousers are… », jamais « my trouser is… ».",
            vocab: [
              ['shirt', 'chemise', 'n'],
              ['trousers', 'pantalon', 'n'],
              ['dress', 'robe', 'n'],
              ['shoes', 'chaussures', 'n'],
              ['jacket', 'veste', 'n'],
              ['coat', 'manteau', 'n'],
              ['hat', 'chapeau', 'n'],
              ['wear', 'porter (un vêtement)', 'v'],
              ['size', 'taille', 'n'],
            ],
            sentences: [
              ['She is wearing a blue dress.', 'Elle porte une robe bleue.'],
              ['These shoes are too small.', 'Ces chaussures sont trop petites.'],
              ['Do you have this in a larger size?', 'L’avez-vous dans une taille plus grande ?'],
            ],
            grammar: [
              {
                topicId: 'present-continuous',
                title: 'Present continuous : ce qui se passe maintenant',
                rule: "« to be » + verbe en -ing décrit une action en cours : « She is wearing a coat » (en ce moment).",
                en: 'She is wearing a blue dress.',
                fr: 'Elle porte une robe bleue.',
                wrong: ['She is wear a blue dress.', 'She wearing a blue dress.', 'She wears a blue dress now.'],
                blank: 'is wearing',
              },
            ],
          },
          {
            id: 'gen-a1-u6-l2',
            title: 'Faire des achats',
            objective: 'Demander un prix, essayer, payer.',
            intro:
              "« How much…? » demande un prix ou une quantité indénombrable ; « How many…? » demande un nombre.",
            vocab: [
              ['shop', 'magasin', 'n'],
              ['price', 'prix', 'n'],
              ['expensive', 'cher', 'adj'],
              ['cheap', 'bon marché', 'adj'],
              ['try on', 'essayer (un vêtement)', 'v'],
              ['cash', 'espèces', 'n'],
              ['card', 'carte bancaire', 'n'],
              ['receipt', 'reçu / ticket', 'n'],
              ['change', 'monnaie', 'n'],
            ],
            sentences: [
              ['How much is this jacket?', 'Combien coûte cette veste ?'],
              ['Can I try it on?', 'Puis-je l’essayer ?'],
              ['I’ll pay by card.', 'Je paierai par carte.'],
            ],
            grammar: [
              {
                topicId: 'how-much-many',
                title: 'How much / How many',
                rule: "« How much » + indénombrable ou prix ; « How many » + nom pluriel dénombrable.",
                en: 'How much is this jacket?',
                fr: 'Combien coûte cette veste ?',
                wrong: ['How many is this jacket?', 'How much cost this jacket?', 'How much this jacket is?'],
                blank: 'How much',
              },
            ],
            dialogue: {
              context: 'Dans une boutique de vêtements.',
              lines: [
                { speaker: 'Customer', en: 'Excuse me, how much is this shirt?', fr: 'Excusez-moi, combien coûte cette chemise ?' },
                { speaker: 'Assistant', en: 'It’s twenty-five pounds.', fr: 'Elle coûte vingt-cinq livres.' },
                { speaker: 'Customer', en: 'Can I try it on?', fr: 'Puis-je l’essayer ?' },
                { speaker: 'Assistant', en: 'Of course. The fitting rooms are over there.', fr: 'Bien sûr. Les cabines sont là-bas.' },
              ],
              statements: [
                { en: 'The shirt costs twenty-five pounds.', isTrue: true, explanation: '« It’s twenty-five pounds. »' },
                { en: 'The customer buys shoes.', isTrue: false, explanation: 'Il s’agit d’une chemise (« this shirt »).' },
              ],
            },
          },
        ],
      },
      {
        id: 'gen-a1-u7',
        title: 'Se déplacer',
        subtitle: 'Transports et directions',
        icon: '🚌',
        lessons: [
          {
            id: 'gen-a1-u7-l1',
            title: 'Les transports',
            objective: 'Dire comment on se déplace.',
            intro:
              "Pour le moyen de transport, l'anglais dit « by bus », « by car », « by train » — sans article. Seule exception : « on foot » (à pied).",
            vocab: [
              ['bus', 'bus', 'n'],
              ['train', 'train', 'n'],
              ['car', 'voiture', 'n'],
              ['bike', 'vélo', 'n'],
              ['plane', 'avion', 'n'],
              ['taxi', 'taxi', 'n'],
              ['ticket', 'billet', 'n'],
              ['station', 'gare / station', 'n'],
              ['on foot', 'à pied', 'phrase'],
            ],
            sentences: [
              ['I go to work by bus.', 'Je vais au travail en bus.'],
              ['She goes to school on foot.', 'Elle va à l’école à pied.'],
              ['The train leaves at six.', 'Le train part à six heures.'],
            ],
            grammar: [
              {
                topicId: 'by-transport',
                title: '« by » + transport, sans article',
                rule: "On dit « by bus », « by car », « by train ». Avec « foot », on dit « on foot ».",
                en: 'I travel by train.',
                fr: 'Je voyage en train.',
                wrong: ['I travel by the train.', 'I travel in train.', 'I travel with train.'],
                blank: 'by',
              },
            ],
          },
          {
            id: 'gen-a1-u7-l2',
            title: 'Demander son chemin',
            objective: 'Comprendre et donner des directions simples.',
            intro:
              "Pour donner une direction, l'anglais utilise l'impératif : « Go straight on », « Turn left ». Pas de sujet devant le verbe.",
            vocab: [
              ['turn left', 'tourner à gauche', 'phrase'],
              ['turn right', 'tourner à droite', 'phrase'],
              ['go straight on', 'continuer tout droit', 'phrase'],
              ['corner', 'coin', 'n'],
              ['street', 'rue', 'n'],
              ['traffic lights', 'feux tricolores', 'n'],
              ['opposite', 'en face de', 'prep'],
              ['far', 'loin', 'adj'],
            ],
            sentences: [
              ['Excuse me, where is the post office?', 'Excusez-moi, où est la poste ?'],
              ['Go straight on and turn left.', 'Continuez tout droit puis tournez à gauche.'],
              ['It is opposite the bank.', 'C’est en face de la banque.'],
            ],
            grammar: [
              {
                topicId: 'imperative',
                title: 'L’impératif',
                rule: "L'impératif anglais est le verbe seul, sans sujet : « Turn right ». La négation se forme avec « Don't » : « Don't turn here ».",
                en: 'Turn right at the traffic lights.',
                fr: 'Tournez à droite aux feux.',
                wrong: ['You turn right at the traffic lights.', 'To turn right at the traffic lights.', 'Turning right at the traffic lights.'],
                blank: 'Turn',
              },
            ],
          },
        ],
      },
      {
        id: 'gen-a1-u8',
        title: 'Météo et loisirs',
        subtitle: 'Le temps qu’il fait et ce qu’on aime faire',
        icon: '☀️',
        lessons: [
          {
            id: 'gen-a1-u8-l1',
            title: 'Le temps qu’il fait',
            objective: 'Décrire la météo.',
            intro:
              "La météo se dit avec « It is… » : « It is hot », « It is raining ». Le sujet « it » est obligatoire même s'il ne désigne rien.",
            vocab: [
              ['sunny', 'ensoleillé', 'adj'],
              ['rainy', 'pluvieux', 'adj'],
              ['cloudy', 'nuageux', 'adj'],
              ['windy', 'venteux', 'adj'],
              ['hot', 'chaud', 'adj'],
              ['cold', 'froid', 'adj'],
              ['warm', 'doux / tiède', 'adj'],
              ['rain', 'pluie / pleuvoir', 'n'],
              ['weather', 'météo / temps', 'n'],
            ],
            sentences: [
              ['It is very hot today.', 'Il fait très chaud aujourd’hui.'],
              ['It is raining in London.', 'Il pleut à Londres.'],
              ['What is the weather like?', 'Quel temps fait-il ?'],
            ],
            grammar: [
              {
                topicId: 'impersonal-it',
                title: 'Le « it » impersonnel',
                rule: "Pour la météo, l'heure et la distance, l'anglais impose le sujet « it » : « It is cold », « It is five o'clock ».",
                en: 'It is cold today.',
                fr: 'Il fait froid aujourd’hui.',
                wrong: ['Is cold today.', 'He is cold today.', 'There is cold today.'],
                blank: 'It',
              },
            ],
          },
          {
            id: 'gen-a1-u8-l2',
            title: 'Loisirs et goûts',
            objective: 'Dire ce qu’on aime faire pendant son temps libre.',
            intro:
              "Après « like », « love », « enjoy » et « hate », le second verbe se met le plus souvent en -ing : « I like reading ».",
            note: {
              title: 'like + verbe en -ing',
              body: "I like swimming. · She enjoys cooking. · They hate waiting. Après « would like », en revanche, on met « to » + infinitif : « I'd like to swim ».",
            },
            vocab: [
              ['read', 'lire', 'v'],
              ['cook', 'cuisiner', 'v'],
              ['travel', 'voyager', 'v'],
              ['swim', 'nager', 'v'],
              ['listen to music', 'écouter de la musique', 'phrase'],
              ['play football', 'jouer au football', 'phrase'],
              ['free time', 'temps libre', 'n'],
              ['hobby', 'loisir', 'n'],
            ],
            sentences: [
              ['I like reading in the evening.', 'J’aime lire le soir.'],
              ['He enjoys cooking for his family.', 'Il aime cuisiner pour sa famille.'],
              ['We don’t like waiting.', 'Nous n’aimons pas attendre.'],
            ],
            grammar: [
              {
                topicId: 'like-ing',
                title: 'like + -ing',
                rule: "Après « like », « love », « enjoy », « hate », le verbe suivant prend -ing : « I like reading ».",
                en: 'I like reading in the evening.',
                fr: 'J’aime lire le soir.',
                wrong: ['I like read in the evening.', 'I like to reading in the evening.', 'I am like reading in the evening.'],
                blank: 'reading',
              },
            ],
          },
        ],
      },
      {
        id: 'gen-a1-u9',
        title: 'Le travail et les études',
        subtitle: 'Parler de son métier, de ses horaires, de ses études',
        icon: '💼',
        lessons: [
          {
            id: 'gen-a1-u9-l1',
            title: 'Parler de son travail',
            objective: 'Dire où l’on travaille et ce que l’on y fait.',
            intro:
              "Pour dire ce que l'on fait, l'anglais utilise « I work as… » (métier) et « I work for… » (employeur) : « I work as an accountant for a construction company ».",
            vocab: [
              ['company', 'entreprise', 'n'],
              ['office', 'bureau', 'n'],
              ['colleague', 'collègue', 'n'],
              ['manager', 'responsable', 'n'],
              ['salary', 'salaire', 'n'],
              ['full-time', 'à temps plein', 'adj'],
              ['part-time', 'à temps partiel', 'adj'],
              ['to hire', 'embaucher', 'v'],
              ['meeting', 'réunion', 'n'],
            ],
            sentences: [
              ['I work as an accountant.', 'Je travaille comme comptable.'],
              ['She works for a construction company.', 'Elle travaille pour une entreprise de construction.'],
              ['We have a meeting every Monday.', 'Nous avons une réunion tous les lundis.'],
            ],
            grammar: [
              {
                topicId: 'work-as-for',
                title: '« work as » ou « work for » ?',
                rule: "« work as » introduit le métier, « work for » introduit l'employeur. On ne dit pas « work like ».",
                en: 'I work as an engineer.',
                fr: 'Je travaille comme ingénieur.',
                wrong: ['I work like an engineer.', 'I work as engineer.', 'I work for an engineer job.'],
                blank: 'as',
              },
            ],
          },
          {
            id: 'gen-a1-u9-l2',
            title: 'Les horaires et les jours de congé',
            objective: 'Parler de ses horaires et poser une question sur le temps de travail.',
            intro:
              "Les horaires se disent avec « from … to … » : « I work from eight to five ». Le jour de congé se dit « day off ».",
            vocab: [
              ['day off', 'jour de congé', 'n'],
              ['holiday', 'vacances / jour férié', 'n'],
              ['overtime', 'heures supplémentaires', 'n'],
              ['shift', 'poste / créneau', 'n'],
              ['break', 'pause', 'n'],
              ['busy', 'occupé', 'adj'],
              ['free', 'libre / disponible', 'adj'],
              ['schedule', 'emploi du temps', 'n'],
            ],
            sentences: [
              ['I work from eight to five.', 'Je travaille de huit heures à dix-sept heures.'],
              ['Tuesday is my day off.', 'Le mardi est mon jour de congé.'],
              ['Are you free on Friday morning?', 'Êtes-vous libre vendredi matin ?'],
            ],
            grammar: [
              {
                topicId: 'from-to-time',
                title: 'from … to … pour un intervalle',
                rule: "Un intervalle horaire s'exprime avec « from » suivi de « to » : « from nine to six ».",
                en: 'She works from nine to six.',
                fr: 'Elle travaille de neuf heures à dix-huit heures.',
                wrong: ['She works from nine until to six.', 'She works of nine to six.', 'She works from nine at six.'],
                blank: 'from',
              },
            ],
          },
          {
            id: 'gen-a1-u9-l3',
            title: 'Les études',
            objective: 'Parler de ses études et de sa formation.',
            intro:
              "« To study » signifie « faire des études / réviser ». Attention : « to learn » veut dire « apprendre » (acquérir), les deux ne sont pas interchangeables.",
            vocab: [
              ['to study', 'étudier', 'v'],
              ['to learn', 'apprendre', 'v'],
              ['university', 'université', 'n'],
              ['degree', 'diplôme', 'n'],
              ['course', 'cours / formation', 'n'],
              ['exam', 'examen', 'n'],
              ['homework', 'devoirs', 'n'],
              ['classroom', 'salle de classe', 'n'],
            ],
            sentences: [
              ['I study economics at university.', 'J’étudie l’économie à l’université.'],
              ['He is learning English online.', 'Il apprend l’anglais en ligne.'],
              ['The exam is next Thursday.', 'L’examen est jeudi prochain.'],
            ],
            grammar: [
              {
                topicId: 'study-vs-learn',
                title: 'study ≠ learn',
                rule: "« study » = suivre des études, réviser ; « learn » = acquérir une compétence. « I study English » (je suis des cours) / « I learn quickly » (j'apprends vite).",
                en: 'I study economics at university.',
                fr: 'J’étudie l’économie à l’université.',
                wrong: [
                  'I learn economics at university since.',
                  'I am study economics at university.',
                  'I study economics in university at.',
                ],
                blank: 'study',
              },
            ],
          },
        ],
      },
    ],
  },
];
